# Generated by the asset_copier plugin
# http://github.com/pelargir/asset_copier

require File.expand_path(File.dirname(__FILE__) + '/../lib/asset_copier')

namespace :image_picker do
  desc "Install files required by image_picker"
  task :install do  
    AssetCopier.copy
  end
end